name: Build and Release App

on:
  push:
    tags:
      - "v*"  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual runs

jobs:
  build:
    name: Build and Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r Speel_schema/requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole \
          --add-data "Speel_schema/src/*:src" Speel_schema/Gui.py
      shell: bash

    - name: Archive build artifacts
      if: startsWith(matrix.os, 'windows')
      run: |
        mkdir -p dist
        mv dist/Gui.exe dist/app-${{ matrix.os }}.exe
      shell: bash

    - name: Archive build artifacts (macOS/Linux)
      if: "!startsWith(matrix.os, 'windows')"
      run: |
        mkdir -p dist
        mv dist/Gui dist/app-${{ matrix.os }}
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.os }}
        path: dist/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-${{ matrix.os }}
        path: dist/

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          dist/app-ubuntu-latest
          dist/app-macos-latest
          dist/app-windows-latest.exe
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
